# autogenerated using templates/2-data/terraform-providers.tf.repo.tpl
terraform {
  required_providers {
    gitlab = {
      source = "gitlabhq/gitlab"
    }
    github = {
      source = "integrations/github"
    }
  }
}
